title: Text2Mesh Text-Driven Neural Stylization for Meshes
description: Text2Mesh stylizes 3D meshes driven by a text prompt.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

paper:
  url: https://www.dropbox.com/s/hbzq7xp95tr1788/text2mesh-preprint.pdf?dl=0
  supp_url: arxiv.com/supp
  affiliations: <sup>1</sup>University Of Chicago, &nbsp; <sup>2</sup>Tel Aviv University
